sound: soc: codecs: tas2560-core: silence the unused variable
kernel/motorola/sdm632/sound/soc/codecs/tas2560-core.c:463:33: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int nBitRate = -1, value = -1, ret = 0;

Signed-off-by: Andrew Hexen <SyberHexen@gmail.com>
Change-Id: Ic61792eacebc9593fdee6b6a2408bb4275007b94