sound: soc: codecs: cirrus_madera: silence the unused variable
../../../../../../kernel/motorola/sdm632/sound/soc/codecs/madera.c:1250:9: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int i, ret;
               ^
../../../../../../kernel/motorola/sdm632/sound/soc/codecs/madera.c:2565:15: error: variable 'ctrl' set but not used [-Werror,-Wunused-but-set-variable]

Signed-off-by: Andrew Hexen <SyberHexen@gmail.com>
Change-Id: I825db189e9605b0ee49b21ca004da3e12c039016